version: "2.4"

services:
  redis:
    image: redis:7.4.0
    restart: unless-stopped

  postgres:
    image: hbontempo/postgres-hll:13.8-alpine-v2.16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
      dockerfile: Dockerfile_dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bin/rails db:create db:migrate db:seed && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3333:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      CACHE_REDIS_URL: redis://redis:6379/2
      RAILS_MASTER_KEY: 83415718363b96e5927f84d24c521640
    volumes:
      - .:/app
volumes:
  pgdata:
