default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= 'postgres://postgres:postgres@postgres:5432/mydb' %>

x-local_database: &x-local-database
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: mysite_development
  <<: *x-local-database

test:
  <<: *default
  database: mysite_test
  <<: *x-local-database

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
